packages:
  - "packages/*"
  - "apps/*"
  - "examples/*"
  - "crates/wasm/pkg"
allowBuilds:
  '@bundled-es-modules/glob': set this to true or false
  '@sentry/cli': set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  style-dictionary: set this to true or false
  wasm-pack: set this to true or false
  workerd: set this to true or false
