/**
 * Demo knowledge graph — 28 nodes representing tech concepts.
 * Used by the force-directed layout experiment.
 */
import type { KnowledgeGraph } from '@substrate-platform/graphics';

export const demoGraph: KnowledgeGraph = {
  nodes: [
    { id: 'react', label: 'React 19', position: [0, 0, 0], weight: 2.5 },
    { id: 'next', label: 'Next.js 16', position: [2, 1, 0], weight: 2.5 },
    { id: 'r3f', label: 'R3F', position: [3, -1, 0], weight: 1.5 },
    { id: 'three', label: 'Three.js', position: [4, 0, 0], weight: 2 },
    { id: 'webgpu', label: 'WebGPU', position: [5, 1, 0], weight: 2.5 },
    { id: 'wgsl', label: 'WGSL', position: [6, 0, 0], weight: 1.5 },
    { id: 'rust', label: 'Rust', position: [-2, -1, 0], weight: 2.5 },
    { id: 'wasm', label: 'WASM', position: [-3, 0, 0], weight: 2 },
    { id: 'simd', label: 'SIMD', position: [-4, 1, 0], weight: 1 },
    { id: 'drizzle', label: 'Drizzle', position: [-1, 2, 0], weight: 1.5 },
    { id: 'pg', label: 'PostgreSQL', position: [-2, 3, 0], weight: 2 },
    { id: 'pgvector', label: 'pgvector', position: [-3, 2, 0], weight: 1 },
    { id: 'turso', label: 'Turso', position: [-3, 4, 0], weight: 1 },
    { id: 'hono', label: 'Hono', position: [1, 3, 0], weight: 1.5 },
    { id: 'cf', label: 'Cloudflare', position: [2, 4, 0], weight: 2 },
    { id: 'do', label: 'Durable Objects', position: [3, 3, 0], weight: 1 },
    { id: 'r2', label: 'R2', position: [4, 4, 0], weight: 1 },
    { id: 'queue', label: 'Queues', position: [0, 4, 0], weight: 1 },
    { id: 'ai', label: 'AI SDK', position: [1, -2, 0], weight: 1.5 },
    { id: 'rag', label: 'RAG', position: [0, -3, 0], weight: 1.5 },
    { id: 'fts', label: 'PG FTS', position: [-1, -3, 0], weight: 1 },
    { id: 'langfuse', label: 'Langfuse', position: [2, -3, 0], weight: 1 },
    { id: 'otel', label: 'OpenTelemetry', position: [3, -4, 0], weight: 1.5 },
    { id: 'sentry', label: 'Sentry', position: [4, -3, 0], weight: 1 },
    { id: 'grafana', label: 'Grafana', position: [5, -4, 0], weight: 1 },
    { id: 'velite', label: 'Velite', position: [-4, -2, 0], weight: 1 },
    { id: 'fumadocs', label: 'Fumadocs', position: [-5, -1, 0], weight: 1 },
    { id: 'orama', label: 'Orama', position: [-5, 0, 0], weight: 1 },
  ],
  edges: [
    { source: 'react', target: 'next' },
    { source: 'react', target: 'r3f' },
    { source: 'r3f', target: 'three' },
    { source: 'three', target: 'webgpu' },
    { source: 'webgpu', target: 'wgsl' },
    { source: 'rust', target: 'wasm' },
    { source: 'wasm', target: 'simd' },
    { source: 'rust', target: 'webgpu' },
    { source: 'next', target: 'drizzle' },
    { source: 'drizzle', target: 'pg' },
    { source: 'pg', target: 'pgvector' },
    { source: 'pg', target: 'turso' },
    { source: 'next', target: 'hono' },
    { source: 'hono', target: 'cf' },
    { source: 'cf', target: 'do' },
    { source: 'cf', target: 'r2' },
    { source: 'cf', target: 'queue' },
    { source: 'next', target: 'ai' },
    { source: 'ai', target: 'rag' },
    { source: 'rag', target: 'fts' },
    { source: 'fts', target: 'pg' },
    { source: 'rag', target: 'pgvector' },
    { source: 'ai', target: 'langfuse' },
    { source: 'langfuse', target: 'otel' },
    { source: 'otel', target: 'grafana' },
    { source: 'otel', target: 'sentry' },
    { source: 'next', target: 'velite' },
    { source: 'velite', target: 'fumadocs' },
    { source: 'velite', target: 'orama' },
    { source: 'next', target: 'react' },
    { source: 'cf', target: 'wasm' },
    { source: 'do', target: 'queue' },
  ],
};
