/**
 * Static article corpus for the minimal-site example.
 *
 * In a full substrate deployment this data is generated by Velite from MDX
 * frontmatter. Here it is hard-coded so the example runs with zero build
 * steps beyond `next build`. The shape mirrors `SearchableDoc` so the same
 * records can feed both the Orama search index and the article routes.
 */

export type Article = {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  tags: string[];
  body: string;
};

export const articles: Article[] = [
  {
    slug: 'design-systems-at-scale',
    title: 'Design Systems at Scale',
    date: '2026-05-02',
    excerpt:
      'How token-driven theming and Radix primitives keep a UI consistent across a dozen surfaces.',
    tags: ['design', 'design-systems', 'css'],
    body: `A design system is not a component library — it is a contract. The tokens are the contract's clauses, the primitives are the boilerplate, and the patterns are the precedent that keeps every team arguing about the same things in the same language.

The substrate stack encodes that contract as CSS custom properties. A single \`--accent-primary\` variable flows from the site theme, through the shared \`@substrate-platform/ui\` stylesheet, into every GlassCard, Button, and Badge. Re-skin the variable and the whole interface follows; no fork, no override cascade, no drift.

Radix primitives handle the interaction layer — focus management, keyboard semantics, ARIA wiring — while class-variance-authority keeps variants declarative. The result is a system where "make this look like everything else" is the default behaviour, not a task.`,
  },
  {
    slug: 'hybrid-rendering-playbook',
    title: 'The Hybrid Rendering Playbook',
    date: '2026-04-18',
    excerpt:
      'Static shells, streaming edges, and Partial Prerendering — choosing a rendering strategy per route.',
    tags: ['nextjs', 'performance', 'rendering'],
    body: `There is no single correct rendering strategy for a content site, only correct per-route choices. A marketing landing page wants to be fully static; an archive with a search box wants a static shell wrapped around a streamed client component; a per-request personalised header wants the edge.

Partial Prerendering makes these choices composable. The route emits a prerendered shell at build time, and the dynamic parts — wrapped in a Suspense boundary — stream in at request time. The user sees the shell instantly; the rest arrives as it resolves. The cache and the network stop being an either/or.

The minimal-site example leans all the way static: every page is prerendered, search runs purely client-side, and OG images are generated on the edge. The feature manifest records that decision in one place so a future maintainer does not have to reverse-engineer it from the route handlers.`,
  },
  {
    slug: 'instant-search-with-orama',
    title: 'Instant Search with Orama',
    date: '2026-03-29',
    excerpt:
      'Zero round-trips, zero servers — building an in-browser search index from static content.',
    tags: ['search', 'orama', 'performance'],
    body: `Orama is a search engine that ships to the browser. You hand it documents at build time, it builds a compact in-memory index, and every query after that is a local function call — no network, no latency floor, no backend to scale.

The substrate content layer wraps that in a single helper: \`createSearchIndex(docs)\` returns an object with a \`search(term)\` method. The archive route passes the static article corpus in as a prop, the client component builds the index on mount, and keystrokes query it synchronously enough to feel instant.

The trade-off is explicit and honest: the index lives in the user's memory, so it scales with the size of your corpus rather than your database. For a personal site that is exactly the right shape; for a hundred-thousand-document catalogue you would graduate to the hybrid FTS-plus-vector pipeline described in the feature manifest.`,
  },
  {
    slug: 'edge-first-og-images',
    title: 'Edge-First OG Images',
    date: '2026-03-11',
    excerpt:
      'Dynamic social cards rendered on the edge with @vercel/og — one route, infinite previews.',
    tags: ['og', 'edge', 'performance'],
    body: `A social card is the first impression a link makes, and statically generating one image per page is tedious. The edge-first alternative renders the card on demand: a single route handler receives a title, composes it into a layout with @vercel/og's ImageResponse, and returns a PNG.

Because the handler runs on the edge runtime, the cold-start cost is measured in milliseconds and the image is cached close to the reader. Every article's metadata points its \`og:image\` at \`/api/og?title=...\`, so adding a new post automatically gets a bespoke card with no build step.

The minimal-site route keeps the layout deliberately spare — a monogram, a title, an accent bar — because the goal is recognisability, not ornament. The same Satori primitives could render charts, covers, or full typographic posters if the brand demanded it.`,
  },
];

/** Look up a single article by its slug. */
export function getArticle(slug: string): Article | undefined {
  return articles.find((article) => article.slug === slug);
}

/** Every slug in the corpus — used to prerender article routes. */
export function getAllSlugs(): string[] {
  return articles.map((article) => article.slug);
}
