#!/usr/bin/env bun
/**
 * check-boundary.ts — Platform boundary enforcement CI gate.
 *
 * Scans the repository for application-specific contamination patterns
 * that must never appear in platform code. Uses precise regex patterns,
 * not a blanket string ban, to avoid false positives on generic English
 * words like "archive" or "lattice".
 *
 * ## Usage
 *
 *   bun run scripts/check-boundary.ts        # CI mode — exits 1 on violation
 *   bun boundary:check                        # via package.json script
 *
 * ## Patterns checked
 *
 *   - Aevum / aevum / AEVUM  (as brand or identifier)
 *   - aevum.dev              (as URL)
 *   - api.aevum.dev          (as API URL)
 *   - aevum-edge             (as resource name)
 *   - aevum-assets           (as resource name)
 *   - aevum-tasks            (as resource name)
 *   - aevum-web              (as service name)
 *   - SITE_BRAND             (as hardcoded constant)
 *   - SUBSYSTEMS             (as hardcoded subsystem list)
 *   - Juwan / juwanh         (as person identifier)
 *   - --aevum-               (as CSS prefix)
 *   - .aevum-                (as CSS class prefix)
 *   - API keys / secrets     (generic credential patterns)
 *
 * ## Excluded paths
 *
 *   - PLATFORM_BOUNDARY.md  (this contract documents the patterns)
 *   - scripts/check-boundary.ts  (this file)
 *   - node_modules / .next / .turbo / dist / target  (build artifacts)
 *   - crates/wasm/pkg/  (generated by wasm-pack)
 *   - bun.lock  (lockfile may contain transitive dep names)
 *   - .git/  (version control internals)
 *
 * Zero external dependencies — uses only Node/Bun builtins.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { argv, cwd, exit } from 'node:process';

// ── Types ───────────────────────────────────────────────────────────

type Violation = {
  file: string;
  line: number;
  col: number;
  pattern: string;
  match: string;
  context: string;
};

// ── Pattern definitions ─────────────────────────────────────────────

/**
 * Each pattern is a precise regex that matches application-specific
 * identifiers, not generic English words.
 *
 * The `message` explains why the match is a violation.
 */
const PATTERNS: Array<{ regex: RegExp; message: string }> = [
  // Brand names — as identifiers, not as substrings in compound words.
  // \b ensures we don't match "aevum" inside another word, but we DO
  // match "aevum-edge", "aevum-assets" etc. because those are
  // compound identifiers with a hyphen boundary.
  {
    regex: /\b[Aa]evum\b|\bAEVUM\b/g,
    message: 'Application-specific brand name "Aevum" in platform code',
  },
  {
    regex: /aevum\.dev/g,
    message: 'Application-specific URL "aevum.dev"',
  },
  {
    regex: /api\.aevum\.dev/g,
    message: 'Application-specific API URL "api.aevum.dev"',
  },
  {
    regex: /aevum-edge/g,
    message: 'Application-specific infrastructure resource "aevum-edge"',
  },
  {
    regex: /aevum-assets/g,
    message: 'Application-specific infrastructure resource "aevum-assets"',
  },
  {
    regex: /aevum-tasks/g,
    message: 'Application-specific infrastructure resource "aevum-tasks"',
  },
  {
    regex: /aevum-web/g,
    message: 'Application-specific service name "aevum-web"',
  },
  {
    regex: /\bSITE_BRAND\b/g,
    message: 'Hardcoded brand constant "SITE_BRAND" — replaced by SiteIdentity',
  },
  {
    regex: /\bSUBSYSTEMS\b/g,
    message: 'Hardcoded subsystem list "SUBSYSTEMS" — application-specific',
  },
  // Person identifiers — case-sensitive to avoid false positives on
  // generic words. "Juwan" as a proper noun, "juwanh" as a handle.
  {
    regex: /\bJuwan\b/g,
    message: 'Person identifier "Juwan" in platform code',
  },
  {
    regex: /\bjuwanh\b/gi,
    message: 'Person identifier "juwanh" in platform code',
  },
  // CSS prefixes.
  {
    regex: /--aevum-/g,
    message: 'Application-specific CSS variable prefix "--aevum-"',
  },
  {
    regex: /\.aevum-/g,
    message: 'Application-specific CSS class prefix ".aevum-"',
  },
  // Generic credential patterns — catch accidental API key commits.
  {
    regex: /\b(sk-|pk-|key_)[A-Za-z0-9]{20,}\b/g,
    message: 'Possible API key or secret — credential in platform code',
  },
  {
    regex: /\b(AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}\b/g,
    message: 'Possible AWS access key ID',
  },
];

// ── Line-level exclusion rules ──────────────────────────────────────

/**
 * Some lines contain legitimate uses of person identifiers that are not
 * contamination — e.g. a GitHub repository URL in Cargo.toml or package.json.
 * These rules suppress violations on matching lines.
 *
 * Each rule is a regex tested against the full line. If it matches,
 * violations on that line are suppressed.
 */
const LINE_EXCLUSIONS: RegExp[] = [
  // GitHub / GitLab / Bitbucket URL — username in a repository URL
  // is not application-specific branding.
  /(?:https?:\/\/)?(?:www\.)?(?:github|gitlab|bitbucket)\.com\/[A-Za-z0-9_-]+/i,
  // package.json / Cargo.toml metadata fields where author name is
  // legitimate project metadata, not application branding.
  /"(?:author|repository|contributors|maintainers)"\s*:/,
  /(?:repository|authors)\s*[:=]/,
];

// ── Excluded paths ──────────────────────────────────────────────────

const EXCLUDED_DIRS = new Set([
  'node_modules',
  '.next',
  '.turbo',
  '.git',
  'dist',
  'target',
  'storybook-static',
  '.cache',
]);

const EXCLUDED_FILES = new Set([
  'PLATFORM_BOUNDARY.md',
  'check-boundary.ts',
  'bun.lock',
  'bun.lockb',
  '.gitignore',
  '.editorconfig',
]);

const EXCLUDED_PATH_PREFIXES = ['crates/wasm/pkg'];

// ── File scanning ───────────────────────────────────────────────────

const SCANNABLE_EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.json',
  '.jsonc',
  '.css',
  '.scss',
  '.md',
  '.mdx',
  '.html',
  '.htm',
  '.yaml',
  '.yml',
  '.toml',
  '.rs',
  '.env',
  '.env.example',
  '.env.local',
  '.sh',
  '.bash',
  '.sql',
  '.txt',
]);

function shouldExclude(filePath: string): boolean {
  const rel = relative(cwd(), filePath).replace(/\\/g, '/');

  for (const prefix of EXCLUDED_PATH_PREFIXES) {
    if (rel.startsWith(prefix)) return true;
  }

  const parts = rel.split('/');
  for (const part of parts) {
    if (EXCLUDED_DIRS.has(part)) return true;
  }

  const basename = parts[parts.length - 1] ?? '';
  if (EXCLUDED_FILES.has(basename)) return true;

  // Skip files without a scannable extension (binary, images, etc.).
  // Check extension by looking for the last dot in the basename.
  // Special-case .env files (which may be .env, .env.example, .env.local).
  if (basename.startsWith('.env')) return false;

  const lastDot = basename.lastIndexOf('.');
  if (lastDot === -1) return true; // No extension — skip.
  const ext = basename.slice(lastDot);
  return !SCANNABLE_EXTENSIONS.has(ext);
}

function scanFile(filePath: string): Violation[] {
  const violations: Violation[] = [];

  let content: string;
  try {
    content = readFileSync(filePath, 'utf-8');
  } catch {
    return violations; // Binary or unreadable — skip.
  }

  const lines = content.split('\n');

  for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
    const line = lines[lineIdx];

    // Check line-level exclusions — e.g. GitHub URLs with usernames
    // are not contamination.
    const isExcludedLine = LINE_EXCLUSIONS.some((re) => re.test(line));
    if (isExcludedLine) continue;

    for (const { regex, message } of PATTERNS) {
      // Reset regex lastIndex (global flag).
      regex.lastIndex = 0;
      let match: RegExpExecArray | null;

      while (true) {
        match = regex.exec(line);
        if (match === null) break;
        const context = line.trim().slice(0, 120);
        violations.push({
          file: relative(cwd(), filePath).replace(/\\/g, '/'),
          line: lineIdx + 1,
          col: match.index + 1,
          pattern: message,
          match: match[0],
          context,
        });
      }
    }
  }

  return violations;
}

function scanDir(dir: string): Violation[] {
  const violations: Violation[] = [];

  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return violations;
  }

  for (const entry of entries) {
    const fullPath = join(dir, entry);

    if (shouldExclude(fullPath)) continue;

    let stat: ReturnType<typeof statSync>;
    try {
      stat = statSync(fullPath);
    } catch {
      continue;
    }

    if (stat.isDirectory()) {
      violations.push(...scanDir(fullPath));
    } else if (stat.isFile()) {
      violations.push(...scanFile(fullPath));
    }
  }

  return violations;
}

// ── Main ────────────────────────────────────────────────────────────

function main(): void {
  const root = argv[2] ?? cwd();

  // Support --help
  if (argv.includes('--help') || argv.includes('-h')) {
    console.log(`
check-boundary — platform boundary enforcement gate

Usage:
  bun run scripts/check-boundary.ts [path]

Scans <path> (default: cwd) for application-specific contamination
patterns. Exits with code 1 if any violations are found.

Patterns: ${PATTERNS.length} rules
Excluded: ${EXCLUDED_DIRS.size} dirs, ${EXCLUDED_FILES.size} files, ${EXCLUDED_PATH_PREFIXES.length} path prefixes
`);
    exit(0);
  }

  console.log('  Boundary check\n');
  console.log(`  Scanning:  ${relative(cwd(), root) || root}`);
  console.log(`  Patterns:  ${PATTERNS.length}`);
  console.log('');

  const violations = scanDir(root);

  if (violations.length === 0) {
    console.log('  \x1b[32m✓ No contamination found.\x1b[0m');
    console.log(`  Scanned ${PATTERNS.length} patterns across all scannable files.\n`);
    exit(0);
  }

  // Report violations.
  console.log(`  \x1b[31m✗ ${violations.length} violation(s) found:\x1b[0m\n`);

  for (const v of violations) {
    console.log(`  \x1b[31m${v.file}:${v.line}:${v.col}\x1b[0m`);
    console.log(`    Pattern: ${v.pattern}`);
    console.log(`    Match:   "${v.match}"`);
    console.log(`    Context: ${v.context}`);
    console.log('');
  }

  console.log('  These patterns indicate application-specific contamination.');
  console.log('  Remove them before merging.\n');

  exit(1);
}

main();
